-- ==========================================
-- OPERATION PAWS: MASTER SCHEMA (National Rollout)
-- ==========================================

-- 1. TABLES (Core Data)
CREATE TABLE IF NOT EXISTS public.paws_dogs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    paws_ref TEXT UNIQUE, -- Generated by trigger
    microchip_id TEXT UNIQUE NOT NULL,
    dog_name TEXT NOT NULL,
    breed TEXT,
    intake_date DATE DEFAULT CURRENT_DATE,
    source_tier INTEGER CHECK (source_tier IN (1, 2, 3)), -- 1: Breeder, 2: Public, 3: Academy
    status TEXT DEFAULT 'Screening' CHECK (status IN ('Screening', 'Academy', 'SAPS_Accepted', 'Withdrawn', 'Welfare_Veto')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.paws_assessments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    dog_id UUID REFERENCES public.paws_dogs(id) ON DELETE CASCADE,
    assessor_name TEXT NOT NULL,
    assessment_type TEXT CHECK (assessment_type IN ('Initial_Screening', 'Academy_Midpoint', 'Final_Selection')),
    score_env_confidence INTEGER CHECK (score_env_confidence BETWEEN 1 AND 5),
    score_toy_drive INTEGER CHECK (score_toy_drive BETWEEN 1 AND 5),
    welfare_status TEXT DEFAULT 'Pass',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ID GENERATION (National Traceability)
CREATE SEQUENCE IF NOT EXISTS paws_id_seq START 1;

CREATE OR REPLACE FUNCTION generate_paws_ref() RETURNS TEXT AS $$
DECLARE
  year_code TEXT;
  seq_num TEXT;
BEGIN
  year_code := to_char(CURRENT_DATE, 'YY');
  seq_num := lpad(nextval('paws_id_seq')::TEXT, 5, '0');
  RETURN 'PAWS-' || year_code || '-' || seq_num;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION set_paws_ref() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.paws_ref IS NULL THEN
    NEW.paws_ref := generate_paws_ref();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_set_paws_ref ON public.paws_dogs;
CREATE TRIGGER tr_set_paws_ref
BEFORE INSERT ON public.paws_dogs
FOR EACH ROW EXECUTE FUNCTION set_paws_ref();

-- 3. SECURITY (Row Level Security)
ALTER TABLE public.paws_dogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.paws_assessments ENABLE ROW LEVEL SECURITY;

-- 4. PUBLIC TRACKER (Anonymized Views)
-- This view allows the public to see stats WITHOUT seeing microchips or names.
CREATE OR REPLACE VIEW public.paws_public_tracker AS
SELECT 
    paws_ref,
    breed,
    intake_date,
    status,
    source_tier
FROM public.paws_dogs;

-- Grant access to the public (anon role)
GRANT SELECT ON public.paws_public_tracker TO anon;
GRANT SELECT ON public.paws_public_tracker TO authenticated;
